name: JukeAlert
main: com.untamedears.JukeAlert.JukeAlert
version: .1
commands:
  jahelp:
    description: Displays help
    usage: /jahelp
  jainfo:
    description: Display information from a snitch
    usage: /jainfo
  jaclear:
    description: Clear information from a snitch
    usage: /jaclear
  janame:
    description: Name a snitch
    usage: /janame
depend: [Citadel]